/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mlib;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.concurrent.Callable;
import javax.swing.table.DefaultTableModel;
import static mlib.Login_form.usnm;

/**
 *
 * @author sarthak
 */
public class SearchName extends javax.swing.JFrame {
    ArrayList<Song> songsList=new ArrayList<>();
    String[][] play2 = new String[5][2];

    /**
     * Creates new form SearchName
     */
    public SearchName() {
        initComponents();
        
        play2[0][0] = "5000";
        play2[0][1] = "sample playlist";
        play2[1][0] = "5001";
        play2[1][1] = "chill songs";
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/dbsproject?zeroDateTimeBehavior=convertToNull","root","1234");
            System.out.print("DAFQ");
            String query1="Select playlist_id, playlist_name from playlistname natural join user1 where user_name like "+"'"+usnm+"';";
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(query1);
            //ComboBoxModel model = new ComboBoxModel();
            Object[] row= new Object[3];
            while(rs.next())
            {
                
                System.out.print(rs.getString("playlist_name"));
                list.addItem(rs.getString("playlist_name"));
                        
            }
            con.close();
            
            
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }
    /*public ArrayList<Song> songList()
    {
        ArrayList<Song> songsList=new ArrayList<>();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/swapnil?zeroDateTimeBehavior=convertToNull","root","swapnils");
            String sname=song.getText();
            String query1="Select song_name,artist_name,album_name,Year,song_id from artist natural join song natural join album where song_name="+"'"+sname+"'";
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(query1);
            Song song;
            while(rs.next())
            {
                song=new Song(rs.getString("song_name"),rs.getString("artist_name"),rs.getString("album_name"),rs.getString("Year"),rs.getInt("song_id"));
                songsList.add(song);
                System.out.println(songsList.get(0).getArtist());
                System.out.println("song \n");
            }
            
            con.close();
            
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        return songsList;
    }
    ArrayList<Song> songs;
    public void showSongs()
    {
         songs=songList();
        DefaultTableModel model=(DefaultTableModel)song_table.getModel();  
        Object[] row= new Object[4];
        for(int i=0;i<songs.size();i++)
        {
            row[0]=songs.get(i).getName();
            System.out.println(row[0]);
            row[1]=songs.get(i).getArtist();
            row[2]=songs.get(i).getAlbum();
            row[3]=songs.get(i).getYear();
            model.addRow(row);
          
        }
        
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        song_table = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        song = new javax.swing.JTextField();
        play = new javax.swing.JButton();
        addtoplaylist = new javax.swing.JButton();
        list = new javax.swing.JComboBox<>();

        jLabel2.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Search");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 50));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Name Of Song");

        search.setBackground(java.awt.Color.black);
        search.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        search.setForeground(new java.awt.Color(0, 204, 0));
        search.setText("Search>");
        search.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        search.setFocusPainted(false);
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        song_table.setBackground(java.awt.Color.black);
        song_table.setForeground(new java.awt.Color(0, 204, 0));
        song_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Album", "Artist", "Genre "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        song_table.setToolTipText("YUHYUH\n");
        jScrollPane1.setViewportView(song_table);

        jButton5.setBackground(java.awt.Color.black);
        jButton5.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 204, 0));
        jButton5.setText("<Back");
        jButton5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton5.setFocusPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Search");

        song.setBackground(new java.awt.Color(0, 0, 153));
        song.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        song.setForeground(java.awt.Color.white);

        play.setBackground(java.awt.Color.black);
        play.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        play.setForeground(new java.awt.Color(0, 204, 0));
        play.setText("Play");
        play.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        play.setFocusPainted(false);
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });

        addtoplaylist.setBackground(java.awt.Color.black);
        addtoplaylist.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        addtoplaylist.setForeground(new java.awt.Color(0, 204, 0));
        addtoplaylist.setText("Add to Playlist");
        addtoplaylist.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        addtoplaylist.setFocusPainted(false);
        addtoplaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtoplaylistActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(addtoplaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134)
                        .addComponent(list, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(play, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(157, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(175, 175, 175))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106)
                        .addComponent(song, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(208, 208, 208))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(song, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(search)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(play)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addtoplaylist)
                    .addComponent(list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addComponent(jButton5)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/dbsproject?zeroDateTimeBehavior=convertToNull","root","1234");
            String aname=song.getText();
             String query1="Select album_name,artist_name,rating,genre, song_name, song_id, year from song natural join album natural join artist where song_name like "+"'%"+aname+"%';";
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(query1);
            DefaultTableModel model=(DefaultTableModel)song_table.getModel();
            model.setRowCount(0);
            Object[] row= new Object[4];
            Song song;
            while(rs.next())
            {
                row[0] = rs.getString("song_name");
                row[1] = rs.getString("album_name");
                row[2] = rs.getString("artist_name");
                row[3] = rs.getString("genre");
                model.addRow(row);
                song=new Song(rs.getString("song_name"),rs.getString("artist_name"),rs.getString("album_name"),rs.getString("Year"),rs.getInt("song_id"));
                songsList.add(song);
                        
            }
            con.close();
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
      
        
    }//GEN-LAST:event_searchActionPerformed

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        // TODO add your handling code here:
         int row=song_table.getSelectedRow();
        System.out.print("HEREINPLAY");
         System.out.println(row);
         System.out.println(songsList.get(row).getId());
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/dbsproject?zeroDateTimeBehavior=convertToNull","root","1234");
            /*Statement st=con.createStatement();
            int row=song_table.getSelectedRow();
            int id1=songsList.get(row-1).getId();
            String query1="select son_id from song where song_name = '"+id1;
            ResultSet rs=st.executeQuery(query1);*/
            CallableStatement mystmt=con.prepareCall("{call updatePlayCount(?)}");
            mystmt.setInt(1,songsList.get(row).getId());
            mystmt.execute();
        }
        catch(Exception e){System.out.println(e);}
         
    }//GEN-LAST:event_playActionPerformed

    private void addtoplaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtoplaylistActionPerformed
        // TODO add your handling code here:
        int row=song_table.getSelectedRow();
        //System.out.print("play[1][0]");
         System.out.println(row);
         System.out.println(songsList.get(row).getId());
         int j=0;
         row = list.getSelectedIndex();
         
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/dbsproject?zeroDateTimeBehavior=convertToNull","root","1234");
            /*Statement st=con.createStatement();
            int row=song_table.getSelectedRow();
            int id1=songsList.get(row-1).getId();
            String query1="select son_id from song where song_name = '"+id1;
            ResultSet rs=st.executeQuery(query1);*/
            
            CallableStatement mystmt=con.prepareCall("insert into playlist ( playlist_id, song_id ) values (" + play2[row][0] + ", " +  songsList.get(row).getId() + " );");
            //mystmt.setInt(1,songsList.get(row).getId());
            mystmt.execute();
        }
        catch(Exception e){System.out.println(e);}
    }//GEN-LAST:event_addtoplaylistActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Search().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchName().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addtoplaylist;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> list;
    private javax.swing.JButton play;
    private javax.swing.JButton search;
    private javax.swing.JTextField song;
    private javax.swing.JTable song_table;
    // End of variables declaration//GEN-END:variables
}
